### ISSUE TITLE
Can't upload NSs through the UI

### ISSUE THREAD

**Issue by rafael-direito** [openslice/io.openslice.portal.web#4]
The upload of NSs through the UI always returns this message: `Experiment Upload - Failed to read uploaded archive! No message
available`. See screenshot below:

![Screenshot 2023-09-27 at 11 43 08](https://github.com/openslice/io.openslice.portal.web/assets/30239227/4c3c70cf-1bcb-497f-a33c-4ab7f5c477e8)

Some further debugging was made by inspecting the browser requests. From this debugging, it was possible to verify that the OSAPI API does not provide any `admin/experiments/` endpoint since the request to this API returned a 404 as you can see in the image below. This was also confirmed by consulting the OpenAPI specification of the OSAPI API.

![Screenshot 2023-09-27 at 11 43 24](https://github.com/openslice/io.openslice.portal.web/assets/30239227/fe011e88-2466-49d0-a5ec-c94c54d15410)

![Screenshot 2023-09-27 at 11 44 45](https://github.com/openslice/io.openslice.portal.web/assets/30239227/3adb42ae-fbab-4d44-af66-2d05883cd398)

From this analysis, I concluded that the endpoint that should be invoked is the following one: `admin/experiments`, and not `admin/experiments/`. Please notice the last `/`.  
The fixing of this issue is quite simple and I can commit on doing it

**Comment by ctranoris** [comment]
thanks rafael cc: @kostistr
