### ISSUE TITLE
A new deployment cannot be added through the NFV portal

### ISSUE THREAD

**Issue by Ioannischatzis** [openslice/io.openslice.portal.web#7]
A new deployment cannot be added through the NFV portal. The error received is 
angular.js:12759     POST http://portal.openslice.io/osapi/admin/deployments/ 404 (Not Found)
while in  
https://github.com/openslice/io.openslice.portal.api/blob/acd3f8530e802b1d367bd358c318fac7434b9f55/src/main/java/portal/api/controller/ArtifactsAPIController.java#L2160
there is a function with the appropriate signature.

**Comment by rafael-direito** [comment]
Hello @Ioannischatzis 
Isn't this issue somehow similar to #4?
Please notice the last `/` in the url used in the Web Portal. The endpoint defined in the Portal API does not have a trailing `/`, and issue #4 was resolved by removing the trailing slash from the url used in the Web Portal to match the one defined in the Portal API.
If my reasoning is correct, we may also solve this by editing the reverse proxy to 'ignore' the trailing `/`.

**Comment by Ioannischatzis** [comment]
Indeed similar to #4
